version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./hospital.db:/app/hospital.db
    environment:
      - PYTHONUNBUFFERED=1
    command: python run.py --with-fixtures
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
